// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yckvgfuwiubxofmhwlur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlja3ZnZnV3aXVieG9mbWh3bHVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NzI2NTcsImV4cCI6MjA1NTU0ODY1N30.iMqfK4CIr01vkRgiCVzs8udJ9T9ALky1j__W9NP_Ruk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);